from fastapi import FastAPI, APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from dotenv import load_dotenv
from starlette.middleware.cors import CORSMiddleware
from motor.motor_asyncio import AsyncIOMotorClient
import os
import logging
import uuid
from pathlib import Path
from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from datetime import datetime, timezone

from mission_data import MISSION_PHASES

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

# MongoDB connection
mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

EMERGENT_LLM_KEY = os.environ.get('EMERGENT_LLM_KEY', '')

app = FastAPI(title="LUNAVIA Mission Control API")
api_router = APIRouter(prefix="/api")


# ---------- Models ----------
class MissionPhase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str
    code: str
    name: str
    t_plus_seconds: int
    duration_seconds: int
    delta_v_ms: float
    altitude_km: float
    velocity_kms: float
    location: str
    objective: str
    description: str


class BriefingRequest(BaseModel):
    phase_id: str
    detail_level: Optional[str] = "standard"  # concise | standard | deep


class MissionLog(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str
    phase_id: str
    mission_time_s: float
    altitude_km: float
    velocity_kms: float
    delta_v_remaining_ms: float
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class MissionLogCreate(BaseModel):
    session_id: str
    phase_id: str
    mission_time_s: float
    altitude_km: float
    velocity_kms: float
    delta_v_remaining_ms: float


# ---------- Routes ----------
@api_router.get("/")
async def root():
    return {"service": "LUNAVIA", "tagline": "THE ROAD TO THE MOON", "status": "nominal"}


@api_router.get("/mission/phases", response_model=List[MissionPhase])
async def get_phases():
    return [MissionPhase(**p) for p in MISSION_PHASES]


@api_router.get("/mission/phases/{phase_id}", response_model=MissionPhase)
async def get_phase(phase_id: str):
    for p in MISSION_PHASES:
        if p["id"] == phase_id:
            return MissionPhase(**p)
    raise HTTPException(status_code=404, detail="Phase not found")


@api_router.post("/mission/briefing")
async def stream_briefing(req: BriefingRequest):
    """Stream a mission briefing generated by Claude Sonnet 5 for the given phase."""
    phase = next((p for p in MISSION_PHASES if p["id"] == req.phase_id), None)
    if not phase:
        raise HTTPException(status_code=404, detail="Phase not found")

    # Optional Emergent-only SDK; the game never calls this route, so its absence must not break the backend.
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage, TextDelta, StreamDone
    except ImportError:
        raise HTTPException(status_code=503, detail="Briefing service unavailable: emergentintegrations is not installed")
    if not EMERGENT_LLM_KEY:
        raise HTTPException(status_code=503, detail="Briefing service unavailable: EMERGENT_LLM_KEY is not set")

    system_msg = (
        "You are the LUNAVIA Mission Control flight director's voice: precise, calm, "
        "documentary tone, NASA-grade. You explain a single phase of an Earth-to-Moon "
        "mission with real orbital-mechanics fidelity. No hype, no emojis, no drama. "
        "Use short paragraphs. Reference real quantities (delta-v, altitude, velocity, "
        "burn duration, angular position of the Moon at TLI ignition, patched-conic hand-offs "
        "when relevant). Write in the same language the user's phase description is written in "
        "(here: Portuguese-Brazilian if any Portuguese words appear; otherwise English)."
    )

    detail_words = {"concise": "80", "standard": "180", "deep": "320"}
    words = detail_words.get(req.detail_level or "standard", "180")

    prompt = (
        f"Mission phase: {phase['code']} — {phase['name']}\n"
        f"Location: {phase['location']}\n"
        f"T+ {phase['t_plus_seconds']} s | Duration: {phase['duration_seconds']} s\n"
        f"Delta-v: {phase['delta_v_ms']} m/s | Altitude: {phase['altitude_km']} km | "
        f"Velocity: {phase['velocity_kms']} km/s\n"
        f"Objective: {phase['objective']}\n"
        f"Context: {phase['description']}\n\n"
        f"Write a ~{words}-word mission briefing in Portuguese-BR, in flight-director voice. "
        f"Explain WHY this phase exists physically (orbital mechanics), what would happen if it "
        f"were skipped, and what the crew/spacecraft is doing in this window."
    )

    session_id = f"briefing-{req.phase_id}-{uuid.uuid4().hex[:8]}"

    chat = LlmChat(
        api_key=EMERGENT_LLM_KEY,
        session_id=session_id,
        system_message=system_msg,
    ).with_model("anthropic", "claude-sonnet-5")

    async def event_generator():
        try:
            async for ev in chat.stream_message(UserMessage(text=prompt)):
                if isinstance(ev, TextDelta):
                    # SSE format: data lines separated by blank line
                    content = ev.content.replace("\n", "\ndata: ")
                    yield f"data: {content}\n\n"
                elif isinstance(ev, StreamDone):
                    yield "event: done\ndata: [DONE]\n\n"
                    break
        except Exception as e:
            logger.exception("briefing stream failed")
            yield f"event: error\ndata: {str(e)}\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


@api_router.post("/mission/log", response_model=MissionLog)
async def log_telemetry(entry: MissionLogCreate):
    obj = MissionLog(**entry.model_dump())
    await db.mission_logs.insert_one(obj.model_dump())
    return obj


@api_router.get("/mission/log/{session_id}", response_model=List[MissionLog])
async def get_logs(session_id: str):
    docs = await db.mission_logs.find({"session_id": session_id}, {"_id": 0}).to_list(500)
    return [MissionLog(**d) for d in docs]


app.include_router(api_router)

app.add_middleware(
    CORSMiddleware,
    allow_credentials=True,
    allow_origins=os.environ.get('CORS_ORIGINS', '*').split(','),
    allow_methods=["*"],
    allow_headers=["*"],
)

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


@app.on_event("shutdown")
async def shutdown_db_client():
    client.close()
